# Generated by Django 4.0.2 on 2023-06-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splatform', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowesCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=70)),
            ],
        ),
    ]
