# Generated by Django 4.0.1 on 2022-03-20 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی')),
                ('address', models.CharField(max_length=100, verbose_name='ادرس')),
                ('line_of_activity', models.CharField(max_length=70, verbose_name='حوزه فعالیت')),
                ('work_experience', models.IntegerField(verbose_name='سابقه کاری')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='Stuff_pics', verbose_name='عکس')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='تایید شده توسط')),
            ],
        ),
    ]
