# Generated by Django 4.1.7 on 2023-03-23 03:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان مقاله")),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="آدرس مقاله"
                    ),
                ),
                ("description", models.TextField(verbose_name="محتوا")),
                (
                    "thumbnail",
                    models.ImageField(upload_to="images", verbose_name="تصویر مقاله"),
                ),
                (
                    "publish",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="زمان انتشار"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("d", "پیش\u200cنویس"), ("p", "منتشر شده")],
                        max_length=1,
                        verbose_name="وضعیت",
                    ),
                ),
            ],
        ),
    ]
