# Generated by Django 4.1.7 on 2023-04-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("slug", models.SlugField()),
                ("position", models.IntegerField()),
                ("is_active", models.BooleanField()),
                ("publish", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.AddField(
            model_name="blog",
            name="category",
            field=models.ManyToManyField(to="blog.category"),
        ),
    ]
