# Generated by Django 4.0.1 on 2022-03-20 03:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('email', models.EmailField(max_length=150, verbose_name='نشانی الکترونیکی')),
                ('person', models.IntegerField(verbose_name='نفرات')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2022, 3, 20, 3, 41, 36, 203154, tzinfo=utc))),
            ],
        ),
    ]
