# Generated by Django 4.0.1 on 2022-03-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_type',
            field=models.CharField(choices=[('DIN', 'dinner'), ('LUN', 'lunch'), ('DRIN', 'drinks')], default='DRIN', max_length=20, verbose_name='نوع غذا'),
        ),
    ]
