# Generated by Django 4.0.1 on 2022-03-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_food_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.CharField(choices=[('dinner', 'dinner'), ('lunch', 'lunch'), ('drink', 'drinks')], default='DRIN', max_length=20, verbose_name='نوع غذا'),
        ),
    ]
