# Generated by Django 4.0.1 on 2022-03-07 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_alter_food_food_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'غذا', 'verbose_name_plural': 'غذاها'},
        ),
    ]
