# Generated by Django 4.0.1 on 2022-03-09 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_alter_food_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='time',
            field=models.DateTimeField(verbose_name='مدت زمان'),
        ),
    ]
