# Generated by Django 4.0.1 on 2022-03-18 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0004_alter_blog_category_alter_blog_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=50, verbose_name='نشانی  الکترونیکی')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Blogs.blog', verbose_name='مقاله مربوطه')),
            ],
        ),
    ]
