# Generated by Django 4.0.1 on 2022-03-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('email', models.EmailField(max_length=100, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=100, verbose_name='تلفن')),
                ('number', models.IntegerField(verbose_name='شماره')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='زمان')),
            ],
        ),
    ]
