# Generated by Django 4.0.1 on 2022-03-10 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'رزرو', 'verbose_name_plural': 'رزروها'},
        ),
    ]
